spring:
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      '[hibernate.show_sql]': true                                       # Log 印出 SQL
      '[hibernate.format_sql]': true                                     # Log 印出 SQL 的排版(會斷行)
      '[hibernate.generate_statistics]': false                            # 顯示 Statements + Commit 的統計數據
      '[hibernate.disables_autocommit]': true                             # 關掉 Auto Commit
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate?useUnicode=true&characterEncoding=utf-8
    username: root
    password: gss@1234
    # Reference: 
    # https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
    hikari:   
     connection-timeout: 60000      # 建立 Connection 在連線時最多可以「等」Connection Pool 多久
     idle-timeout: 600000           # 被建立的 Connection 能在 Pool 裡閒置多久
     keepalive-time: 30000          # 確保 Connection 不會被 DBMS 回收的時間(需小於 maxLifetime，只會發生在 idle Connection)
     max-lifetime: 600000           # 已建立的 Connection 在 Pool 能存在多久 (只有 Closed 會被刪)
     minimum-idle: 10               # 最少要持有幾個 Idle Connection(需小於 maximumPoolSize)
     maximum-pool-size: 10          # Pool 內能存放的最大連線數 (依情況調整大小)
     leak-detection-threshold: 5000 # 偵測是否有 Connection Leak(沒關的 Connection)
     auto-commit: false
     data-source-properties:
       # MySQL 特定的設定(vendor specific)
       cachePrepStmts: true
       useServerPrepStmts: true
       prepStmtCacheSize: 256

